CREATE TABLE `ACCESS_LOG` (
    `SEQ` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '순번',
    `USER_ID` VARCHAR(50) NULL COMMENT '사용자ID',
    `SESSION_ID` VARCHAR(100) NULL COMMENT '세션ID',
    `LOGIN_DATE` DATETIME NULL COMMENT '로그인시간',
    `LOGOUT_DATE` DATETIME NULL COMMENT '로그아웃시간',
    PRIMARY KEY (`SEQ`) USING BTREE,
    INDEX `IDX_ACCESS_LOG_IN_01` (`SESSION_ID`) USING BTREE
)
COMMENT='접속로그 로그'
ENGINE=InnoDB
;
