CREATE TABLE `USER` (
    `USER_ID` VARCHAR(20) NOT NULL COMMENT '사용자ID',
    `USER_NM` VARCHAR(30) NOT NULL COMMENT '사용자명',
    `USER_PASSWORD` VARCHAR(120) NULL DEFAULT NULL COMMENT '사용자 비밀번호',
    `MOBILE_NO` VARCHAR(20) NULL DEFAULT NULL COMMENT '핸드폰번호',
    `TEL_NO` VARCHAR(20) NULL DEFAULT NULL COMMENT '전화번호',
    `EMAIL` VARCHAR(50) NULL DEFAULT NULL COMMENT '이메일',
    `ZIP_CD` VARCHAR(5) NULL DEFAULT NULL COMMENT '우편번호',
    `ADDR1` VARCHAR(100) NULL DEFAULT NULL COMMENT '주소1',
    `ADDR2` VARCHAR(200) NULL DEFAULT NULL COMMENT '주소2',
    `USE_YN` VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
    `REG_USER_ID` VARCHAR(20) NULL DEFAULT NULL COMMENT '등록자',
    `REG_DT` DATETIME NULL DEFAULT NULL COMMENT '등록일시',
    `MOD_USER_ID` VARCHAR(20) NULL DEFAULT NULL COMMENT '수정자',
    `MOD_DT` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    PRIMARY KEY (`USER_ID`)
)
COMMENT='사용자'
ENGINE=InnoDB
; 